//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintInvoice.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unship_single_package_data.sql")]
        public string UnshipSinglePackageDataQuery {
            get {
                return ((string)(this["UnshipSinglePackageDataQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unship_batch_package_data.sql")]
        public string UnshipBatchPackageDataQuery {
            get {
                return ((string)(this["UnshipBatchPackageDataQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("unshipped.sql")]
        public string UnshippedQuery {
            get {
                return ((string)(this["UnshippedQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reprint.sql")]
        public string ReprintQuery {
            get {
                return ((string)(this["ReprintQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reprint_single_package_data.sql")]
        public string ReprintSinglePackageDataQuery {
            get {
                return ((string)(this["ReprintSinglePackageDataQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reprint_batch_package_data.sql")]
        public string ReprintBatchPackageDataQuery {
            get {
                return ((string)(this["ReprintBatchPackageDataQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("repair.sql")]
        public string RepairQuery {
            get {
                return ((string)(this["RepairQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("last_batches.sql")]
        public string LastBatchesQuery {
            get {
                return ((string)(this["LastBatchesQuery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int InvoiceLoaderCacheSize {
            get {
                return ((int)(this["InvoiceLoaderCacheSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int PrintJobQueueMaxSize {
            get {
                return ((int)(this["PrintJobQueueMaxSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SaveStatusQueueMaxSize {
            get {
                return ((int)(this["SaveStatusQueueMaxSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is a TEST installation of the LabelService Printer. If you are seeing this m" +
            "essage, then you are missing a configuration file. Contact webmaster@mnmglobal.c" +
            "om for this file.")]
        public string HelpText {
            get {
                return ((string)(this["HelpText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int ElementsOrderedFieldIndex {
            get {
                return ((int)(this["ElementsOrderedFieldIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int InvoiceSequenceNumberFontSize {
            get {
                return ((int)(this["InvoiceSequenceNumberFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("375")]
        public int InvoiceSequenceNumberX {
            get {
                return ((int)(this["InvoiceSequenceNumberX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int InvoiceSequenceNumberY {
            get {
                return ((int)(this["InvoiceSequenceNumberY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int MasterPickListFontSize {
            get {
                return ((int)(this["MasterPickListFontSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int InvoiceSequenceNumberXPackJacket {
            get {
                return ((int)(this["InvoiceSequenceNumberXPackJacket"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int InvoiceSequenceNumberYPackJacket {
            get {
                return ((int)(this["InvoiceSequenceNumberYPackJacket"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devsvn.mnmglobal.com/scripts/label_service/web/NeedConfig.php?wsdl")]
        public string LabelServiceUrl {
            get {
                return ((string)(this["LabelServiceUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_DEFAULT-ID_")]
        public string PrintStationId {
            get {
                return ((string)(this["PrintStationId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PrintApp for LabelService _DEFAULT_. Unship operation: refund postage, set package status to LABELABLE , set orders status to last status before LABELED.          ***Use the ""Add Invoices"" and ""Last Batches"" buttons to load packages to ""unship"".         NOTE: Packages will start labeling and be printable within 5 minutes.")]
        public string UnshipHelpText {
            get {
                return ((string)(this["UnshipHelpText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"PrintApp for LabelService _DEFAULT_. List below represents packages remaining to be picked. (Only a certain number of packages are auto-picked for labeling each morning.) Usually you would pick the EXPRESS packages first, or specific orders that need to be shipped right away.")]
        public string UnshippedHelpText {
            get {
                return ((string)(this["UnshippedHelpText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintApp for LabelService _DEFAULT_. Repair Errors (BETA). Use this to repair pac" +
            "kages with statuses of ERROR, (or various LOCKED and older than 10 minutes).")]
        public string RepairHelpText {
            get {
                return ((string)(this["RepairHelpText"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrintApp for LabelService _DEFAULT_. Reprint previous batches or orders. This is " +
            "useful if you printed to the wrong printer, printer crashed, printer-out-of-ink," +
            " etc. \n                \n                ***BE CAREFUL NOT TO PRINT/PACK DUPLICAT" +
            "E ORDERS***")]
        public string ReprintHelpText {
            get {
                return ((string)(this["ReprintHelpText"]));
            }
        }
    }
}
